### PR TITLE
2022 Project Update

### LINKED ISSUE #403: No more proper releases?
The last release is 2 years ago and there are a lot of changes that could use a versioned release

### PR DESCRIPTION
**Pull request by TheLQ**
Please approve @hoerup and @cypherke . Thank you for your significant contributions to this project. More PRs to follow in the next weeks fixing bugs. Then we can fix #403 .

* In AUTHORS, list maintainers. Replace all copyright/@author/etc with The PircBotX Project Authors. This has been a team project
* In README
  * Improved project description
  * Expanded feature list to everything
  * Cleanup old headers
  * Cleanup license section
  * Improved wording
* In POM
  * Refactored for Maven's 2022 ecosystem 
  * Updated all build dependencies
  * Support [reproducible builds](https://reproducible-builds.org/). One benifit is `mvn site` no longer updates a timestamp in every single file
* Release Management
  * [ ] Create dedicated release signing key in src/etc/release-key.gpg
  * Revert Maven package group to original org.pircbotx for independence reasons. Recently bought pircbotx.org for 10 years.
  * I nominate @hoerup to share with my Sonatype OSSRH account, new private key, and domain registrar account to [reduce our bus factor](https://en.wikipedia.org/wiki/Bus_factor). [Just be mindful of supply chain attacks](https://github.blog/2021-11-15-githubs-commitment-to-npm-ecosystem-security/).
  * Leave new jitpack.io repo alone for now to avoid duplicate repos
  * Replace Travis CI (RIP) with Github Actions
* [ ] Deploy 2.2 to Maven Central Prod

  * Compared
    ```shell
    mkdir jitpack maven
    cd jitpack
    wget \
        https://jitpack.io/com/github/pircbotx/pircbotx/2.2/pircbotx-2.2.pom \
        https://jitpack.io/com/github/pircbotx/pircbotx/2.2/pircbotx-2.2.jar
    sha256sum * | tee ../hashes.txt
    # 28f301520ca8ac12099f31acb64de92cc084253f691fc8a2fd165660da82bd77  pircbotx-2.2.pom
    # 004b6f46666f8b256a786b63ffc070afca77ce59938e34ef3fd76bfabc851ab9  pircbotx-2.2.jar
    
    cd ../maven
    wget $someStagingUrlTODO
    sha256sum -c ../hashes.txt
    # pircbotx-2.2.jart: OK
    ```

PircBotX turns 12 soon. My first commit was [August 2010](https://github.com/pircbotx/pircbotx/commit/21e62c5339366ea66b83a45e495b45ea7e4b0f44) as a High School Senior.

### CODE REVIEW

**Comment by TheLQ** [comment]
Been sitting on this for a while blocked on the release and gpg task. Will just merge what's done instead.

**Review by hoerup — APPROVED** [review]
Looks good

**Review by tobciu — APPROVED** [review]
looks good

**Comment by Cypherke** [comment]
sorry was on a vacation... very nice change. Thx!

**Pull request merged**
