### PR TITLE
Sending password to server without local logging password

### PR DESCRIPTION
**Pull request by MasterLogick**
I think it will be more securely. Then password is sended to server logger says "PASS **********" instead of "PASS your_secret_password"

### CODE REVIEW

**Comment by TheLQ** [comment]
LGTM, users can log the config option if they want to see the raw password

@hoerup ?

**Comment by hoerup** [comment]
I would rather do another approach, and take some of the good ideas from #368 where it tries to cover more of the scenarios where a password might be logged

**Comment by TheLQ** [comment]
That one seemed expensive to me. Nowadays using dedicated methods for passwords is normal (see char[] arrays, SecureString in powershell, etc). We could add similar methods for Oper and Join (since when did join have passwords?) that #386 covers.

**Comment by hoerup** [comment]
If a channel is password protected then you add the password to the join command. We should also handle the Nickserv identify case

**Comment by hoerup** [comment]
I have made an alternative implementation in #388

**Comment by hoerup** [comment]
#388 is merged so om closing this

**Pull request closed without merging**
