### PR TITLE
Add QuietListEvent and tests

### PR DESCRIPTION
**Pull request by jeaye**
This follows the existing BanListEvent and has been tested on Libera.

### CODE REVIEW

**Comment by jeaye** [comment]
Hi there! Is there any interest in this? I'd like to get it merged/released so I can start using it without maintaining a fork.

**Comment by hoerup** [comment]
Sorry for the delay - looks good

**Comment by jeaye** [comment]
Thanks! Are you open to deploying this to maven so it can be used? Could be 2.3 or a snapshot; either works for me.

**Comment by jeaye** [comment]
Ahh, looks like I can use this: https://jitpack.io/#pircbotx/pircbotx/-SNAPSHOT

Cheers.

**Pull request merged**
